-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.caja
(
    "idCaja" uuid NOT NULL DEFAULT gen_random_uuid(),
    "sedeId" uuid,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    CONSTRAINT caja_pkey PRIMARY KEY ("idCaja"),
    CONSTRAINT "caja_sedeId_key" UNIQUE ("sedeId")
);

CREATE TABLE IF NOT EXISTS public."cateInsumo"
(
    "idCateInsumo" uuid NOT NULL DEFAULT gen_random_uuid(),
    "insumoId" uuid,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    CONSTRAINT "cateInsumo_pkey" PRIMARY KEY ("idCateInsumo")
);

CREATE TABLE IF NOT EXISTS public."cateProducto"
(
    "idCateProducto" uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    area character varying(50) COLLATE pg_catalog."default" DEFAULT 'COCINA'::character varying,
    CONSTRAINT "cateProducto_pkey" PRIMARY KEY ("idCateProducto")
);

CREATE TABLE IF NOT EXISTS public.cliente
(
    "idCliente" uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying(150) COLLATE pg_catalog."default",
    telefono character varying(20) COLLATE pg_catalog."default",
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    documento character varying(20) COLLATE pg_catalog."default",
    "tipoDocumento" character varying(20) COLLATE pg_catalog."default" DEFAULT '1'::character varying,
    CONSTRAINT cliente_pkey PRIMARY KEY ("idCliente")
);

COMMENT ON COLUMN public.cliente."tipoDocumento"
    IS 'Codigo SUNAT: 1=DNI, 6=RUC, 4=Carnet Extranjeria';

CREATE TABLE IF NOT EXISTS public.comprobante
(
    "idComprobante" uuid NOT NULL DEFAULT gen_random_uuid(),
    "pedidoId" uuid NOT NULL,
    "clienteId" uuid NOT NULL,
    tipo character varying(2) COLLATE pg_catalog."default" NOT NULL,
    serie character varying(4) COLLATE pg_catalog."default" NOT NULL,
    correlativo integer NOT NULL,
    "fechaEmision" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    "totalGravada" numeric(10, 2) NOT NULL DEFAULT 0,
    "totalIgv" numeric(10, 2) NOT NULL DEFAULT 0,
    "totalImporte" numeric(10, 2) NOT NULL DEFAULT 0,
    "xmlFilename" text COLLATE pg_catalog."default",
    "cdrFilename" text COLLATE pg_catalog."default",
    "estadoSunat" character varying(20) COLLATE pg_catalog."default" DEFAULT 'PENDIENTE'::character varying,
    observaciones text COLLATE pg_catalog."default",
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    CONSTRAINT comprobante_pkey PRIMARY KEY ("idComprobante")
);

COMMENT ON COLUMN public.comprobante.tipo
    IS '01=Factura, 03=Boleta';

COMMENT ON COLUMN public.comprobante."estadoSunat"
    IS 'PENDIENTE, ENVIADO, ACEPTADO, RECHAZADO';

CREATE TABLE IF NOT EXISTS public."detalleOrdenProduccion"
(
    "idDetalleOrden" uuid NOT NULL DEFAULT gen_random_uuid(),
    "productoId" uuid NOT NULL,
    "cantidadSolicitada" integer NOT NULL,
    "cantidadProducida" integer DEFAULT 0,
    personalizacion jsonb,
    CONSTRAINT "detalleOrdenProduccion_pkey" PRIMARY KEY ("idDetalleOrden")
);

CREATE TABLE IF NOT EXISTS public."detallePedido"
(
    "idDetallePedido" uuid NOT NULL DEFAULT gen_random_uuid(),
    "pedidoId" uuid NOT NULL,
    "productoId" uuid NOT NULL,
    cantidad integer NOT NULL,
    "precioUnitario" numeric(10, 2) NOT NULL,
    subtotal numeric(10, 2) NOT NULL,
    notas text COLLATE pg_catalog."default",
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    estado character varying(20) COLLATE pg_catalog."default" DEFAULT 'PENDIENTE'::character varying,
    CONSTRAINT "detallePedido_pkey" PRIMARY KEY ("idDetallePedido")
);

CREATE TABLE IF NOT EXISTS public."detalleReceta"
(
    "idDetalleReceta" uuid NOT NULL DEFAULT gen_random_uuid(),
    "recetaId" uuid NOT NULL,
    "insumoId" uuid NOT NULL,
    "cantidadRequerida" numeric(12, 4) NOT NULL,
    CONSTRAINT "detalleReceta_pkey" PRIMARY KEY ("idDetalleReceta")
);

CREATE TABLE IF NOT EXISTS public."detalleSoli"
(
    "idDetalleSoli" uuid NOT NULL DEFAULT gen_random_uuid(),
    "soliInventarioId" uuid NOT NULL,
    "productoId" uuid,
    "insumoId" uuid,
    cantidad numeric(10, 2) NOT NULL,
    "cantidadAprobada" double precision,
    "creadoEn" bigint,
    CONSTRAINT "detalleSoli_pkey" PRIMARY KEY ("idDetalleSoli")
);

CREATE TABLE IF NOT EXISTS public.empleado
(
    "idEmpleado" uuid NOT NULL DEFAULT gen_random_uuid(),
    "sedeId" uuid NOT NULL,
    nombres character varying(150) COLLATE pg_catalog."default" NOT NULL,
    dni character varying(20) COLLATE pg_catalog."default",
    telefono character varying(20) COLLATE pg_catalog."default",
    estado boolean DEFAULT true,
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    CONSTRAINT empleado_pkey PRIMARY KEY ("idEmpleado")
);

CREATE TABLE IF NOT EXISTS public."imgProducto"
(
    "idImgProducto" uuid NOT NULL DEFAULT gen_random_uuid(),
    "productoId" uuid NOT NULL,
    url text COLLATE pg_catalog."default" NOT NULL,
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    CONSTRAINT "imgProducto_pkey" PRIMARY KEY ("idImgProducto")
);

CREATE TABLE IF NOT EXISTS public.insumo
(
    "idInsumo" uuid NOT NULL DEFAULT gen_random_uuid(),
    "inventarioId" uuid,
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "unidadMedida" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "costoPromedio" numeric(10, 4) DEFAULT 0,
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    "cateInsumoId" uuid,
    CONSTRAINT insumo_pkey PRIMARY KEY ("idInsumo")
);

CREATE TABLE IF NOT EXISTS public.inventario
(
    "idInventario" uuid NOT NULL DEFAULT gen_random_uuid(),
    "sedeId" uuid NOT NULL,
    stock numeric(12, 4) NOT NULL DEFAULT 0,
    "stockMinimo" numeric(12, 4) DEFAULT 5,
    "ultimoMovimiento" integer DEFAULT (EXTRACT(epoch FROM now()))::integer,
    CONSTRAINT inventario_pkey PRIMARY KEY ("idInventario")
);

CREATE TABLE IF NOT EXISTS public.mesa
(
    "idMesa" uuid NOT NULL DEFAULT gen_random_uuid(),
    "pisoId" uuid NOT NULL,
    numero character varying(10) COLLATE pg_catalog."default" NOT NULL,
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    estado character varying(20) COLLATE pg_catalog."default" DEFAULT 'DISPONIBLE'::character varying,
    CONSTRAINT mesa_pkey PRIMARY KEY ("idMesa")
);

COMMENT ON COLUMN public.mesa.estado
    IS 'Estado de la mesa: DISPONIBLE u OCUPADA';

CREATE TABLE IF NOT EXISTS public."moviCaja"
(
    "idMoviCaja" uuid NOT NULL DEFAULT gen_random_uuid(),
    "cajaId" uuid NOT NULL,
    tipo character varying(20) COLLATE pg_catalog."default" NOT NULL,
    monto numeric(10, 2) NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    CONSTRAINT "moviCaja_pkey" PRIMARY KEY ("idMoviCaja")
);

CREATE TABLE IF NOT EXISTS public."moviInventario"
(
    "idMovInventario" uuid NOT NULL DEFAULT gen_random_uuid(),
    "inventarioId" uuid NOT NULL,
    tipo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    cantidad numeric(12, 4) NOT NULL,
    motivo text COLLATE pg_catalog."default",
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    CONSTRAINT "moviInventario_pkey" PRIMARY KEY ("idMovInventario")
);

CREATE TABLE IF NOT EXISTS public.notificacion
(
    "idNotificacion" uuid NOT NULL DEFAULT gen_random_uuid(),
    "usuarioId" uuid NOT NULL,
    mensaje text COLLATE pg_catalog."default" NOT NULL,
    leido boolean DEFAULT false,
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    CONSTRAINT notificacion_pkey PRIMARY KEY ("idNotificacion")
);

CREATE TABLE IF NOT EXISTS public."ordenProduccion"
(
    "idOrden" uuid NOT NULL DEFAULT gen_random_uuid(),
    "sedeId" uuid NOT NULL,
    "detalleOrdenProduccionId" uuid,
    "fechaSolicitud" integer DEFAULT (EXTRACT(epoch FROM now()))::integer,
    "fechaEntrega" integer,
    estado character varying(50) COLLATE pg_catalog."default" DEFAULT 'PENDIENTE'::character varying,
    observaciones text COLLATE pg_catalog."default",
    CONSTRAINT "ordenProduccion_pkey" PRIMARY KEY ("idOrden")
);

CREATE TABLE IF NOT EXISTS public.pago
(
    "idPago" uuid NOT NULL DEFAULT gen_random_uuid(),
    "pedidoId" uuid NOT NULL,
    "sesionCajaId" uuid,
    monto numeric(10, 2) NOT NULL,
    metodo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    CONSTRAINT pago_pkey PRIMARY KEY ("idPago")
);

CREATE TABLE IF NOT EXISTS public.pedido
(
    "idPedido" uuid NOT NULL DEFAULT gen_random_uuid(),
    "mesaId" uuid,
    "clienteId" uuid,
    "empleadoId" uuid,
    orden character varying(10) COLLATE pg_catalog."default",
    total numeric(10, 2) DEFAULT 0,
    estado character varying(20) COLLATE pg_catalog."default" DEFAULT 'PENDIENTE'::character varying,
    "esPersonalizado" boolean DEFAULT false,
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    CONSTRAINT pedido_pkey PRIMARY KEY ("idPedido")
);

CREATE TABLE IF NOT EXISTS public.permiso
(
    "idPermiso" uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    CONSTRAINT permiso_pkey PRIMARY KEY ("idPermiso"),
    CONSTRAINT permiso_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.piso
(
    "idPiso" uuid NOT NULL DEFAULT gen_random_uuid(),
    "sedeId" uuid NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    CONSTRAINT piso_pkey PRIMARY KEY ("idPiso")
);

CREATE TABLE IF NOT EXISTS public.producto
(
    "idProducto" uuid NOT NULL DEFAULT gen_random_uuid(),
    "inventarioId" uuid,
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    precio numeric(10, 2) NOT NULL,
    estado boolean DEFAULT true,
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    "cateProductoId" uuid,
    CONSTRAINT producto_pkey PRIMARY KEY ("idProducto")
);

CREATE TABLE IF NOT EXISTS public.receta
(
    "idReceta" uuid NOT NULL DEFAULT gen_random_uuid(),
    "productoId" uuid NOT NULL,
    nombre character varying(150) COLLATE pg_catalog."default",
    "cantidadProducida" integer DEFAULT 1,
    activo boolean DEFAULT true,
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    CONSTRAINT receta_pkey PRIMARY KEY ("idReceta")
);

CREATE TABLE IF NOT EXISTS public.rol
(
    "idRol" uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    CONSTRAINT rol_pkey PRIMARY KEY ("idRol"),
    CONSTRAINT rol_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public."rolPermiso"
(
    "rolId" uuid NOT NULL,
    "permisoId" uuid NOT NULL,
    CONSTRAINT "rolPermiso_pkey" PRIMARY KEY ("rolId", "permisoId")
);

CREATE TABLE IF NOT EXISTS public.sede
(
    "idSede" uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    direccion text COLLATE pg_catalog."default",
    "esPrincipal" boolean DEFAULT false,
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    CONSTRAINT sede_pkey PRIMARY KEY ("idSede")
);

CREATE TABLE IF NOT EXISTS public."sesionCaja"
(
    "idSesionCaja" uuid NOT NULL DEFAULT gen_random_uuid(),
    "cajaId" uuid NOT NULL,
    "montoApertura" numeric(10, 2) NOT NULL,
    "montoCierre" numeric(10, 2),
    "fechaApertura" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    "fechaCierre" integer,
    CONSTRAINT "sesionCaja_pkey" PRIMARY KEY ("idSesionCaja")
);

CREATE TABLE IF NOT EXISTS public."soliInventario"
(
    "idSoliInventario" uuid NOT NULL DEFAULT gen_random_uuid(),
    "sedeSolicitanteId" uuid NOT NULL,
    "sedeProveedoraId" uuid,
    tipo character varying(50) COLLATE pg_catalog."default" DEFAULT 'REPOSICION'::character varying,
    estado character varying(20) COLLATE pg_catalog."default" DEFAULT 'PENDIENTE'::character varying,
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    CONSTRAINT "soliInventario_pkey" PRIMARY KEY ("idSoliInventario")
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    "idUsuario" uuid NOT NULL DEFAULT gen_random_uuid(),
    "empleadoId" uuid NOT NULL,
    "rolId" uuid NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "creadoEn" integer NOT NULL DEFAULT (EXTRACT(epoch FROM now()))::integer,
    CONSTRAINT usuario_pkey PRIMARY KEY ("idUsuario"),
    CONSTRAINT usuario_email_key UNIQUE (email),
    CONSTRAINT "usuario_empleadoId_key" UNIQUE ("empleadoId")
);

ALTER TABLE IF EXISTS public.caja
    ADD CONSTRAINT "caja_sedeId_fkey" FOREIGN KEY ("sedeId")
    REFERENCES public.sede ("idSede") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "caja_sedeId_key"
    ON public.caja("sedeId");


ALTER TABLE IF EXISTS public."cateInsumo"
    ADD CONSTRAINT "cateInsumo_insumoId_fkey" FOREIGN KEY ("insumoId")
    REFERENCES public.insumo ("idInsumo") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comprobante
    ADD CONSTRAINT "comprobante_clienteId_fkey" FOREIGN KEY ("clienteId")
    REFERENCES public.cliente ("idCliente") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comprobante
    ADD CONSTRAINT "comprobante_pedidoId_fkey" FOREIGN KEY ("pedidoId")
    REFERENCES public.pedido ("idPedido") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."detalleOrdenProduccion"
    ADD CONSTRAINT "detalleOrdenProduccion_productoId_fkey" FOREIGN KEY ("productoId")
    REFERENCES public.producto ("idProducto") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."detallePedido"
    ADD CONSTRAINT "detallePedido_pedidoId_fkey" FOREIGN KEY ("pedidoId")
    REFERENCES public.pedido ("idPedido") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."detallePedido"
    ADD CONSTRAINT "detallePedido_productoId_fkey" FOREIGN KEY ("productoId")
    REFERENCES public.producto ("idProducto") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."detalleReceta"
    ADD CONSTRAINT "detalleReceta_insumoId_fkey" FOREIGN KEY ("insumoId")
    REFERENCES public.insumo ("idInsumo") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."detalleReceta"
    ADD CONSTRAINT "detalleReceta_recetaId_fkey" FOREIGN KEY ("recetaId")
    REFERENCES public.receta ("idReceta") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."detalleSoli"
    ADD CONSTRAINT "detalleSoli_insumoId_fkey" FOREIGN KEY ("insumoId")
    REFERENCES public.insumo ("idInsumo") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."detalleSoli"
    ADD CONSTRAINT "detalleSoli_productoId_fkey" FOREIGN KEY ("productoId")
    REFERENCES public.producto ("idProducto") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."detalleSoli"
    ADD CONSTRAINT "detalleSoli_soliInventarioId_fkey" FOREIGN KEY ("soliInventarioId")
    REFERENCES public."soliInventario" ("idSoliInventario") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.empleado
    ADD CONSTRAINT "empleado_sedeId_fkey" FOREIGN KEY ("sedeId")
    REFERENCES public.sede ("idSede") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."imgProducto"
    ADD CONSTRAINT "imgProducto_productoId_fkey" FOREIGN KEY ("productoId")
    REFERENCES public.producto ("idProducto") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.insumo
    ADD CONSTRAINT "insumo_cateInsumoId_fkey" FOREIGN KEY ("cateInsumoId")
    REFERENCES public."cateInsumo" ("idCateInsumo") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.insumo
    ADD CONSTRAINT "insumo_inventarioId_fkey" FOREIGN KEY ("inventarioId")
    REFERENCES public.inventario ("idInventario") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inventario
    ADD CONSTRAINT "inventario_sedeId_fkey" FOREIGN KEY ("sedeId")
    REFERENCES public.sede ("idSede") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.mesa
    ADD CONSTRAINT "mesa_pisoId_fkey" FOREIGN KEY ("pisoId")
    REFERENCES public.piso ("idPiso") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."moviCaja"
    ADD CONSTRAINT "moviCaja_cajaId_fkey" FOREIGN KEY ("cajaId")
    REFERENCES public.caja ("idCaja") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."moviInventario"
    ADD CONSTRAINT "moviInventario_inventarioId_fkey" FOREIGN KEY ("inventarioId")
    REFERENCES public.inventario ("idInventario") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.notificacion
    ADD CONSTRAINT "notificacion_usuarioId_fkey" FOREIGN KEY ("usuarioId")
    REFERENCES public.usuario ("idUsuario") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."ordenProduccion"
    ADD CONSTRAINT "ordenProduccion_detalleOrdenProduccionId_fkey" FOREIGN KEY ("detalleOrdenProduccionId")
    REFERENCES public."detalleOrdenProduccion" ("idDetalleOrden") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."ordenProduccion"
    ADD CONSTRAINT "ordenProduccion_sedeId_fkey" FOREIGN KEY ("sedeId")
    REFERENCES public.sede ("idSede") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pago
    ADD CONSTRAINT "pago_pedidoId_fkey" FOREIGN KEY ("pedidoId")
    REFERENCES public.pedido ("idPedido") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pago
    ADD CONSTRAINT "pago_sesionCajaId_fkey" FOREIGN KEY ("sesionCajaId")
    REFERENCES public."sesionCaja" ("idSesionCaja") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pedido
    ADD CONSTRAINT "pedido_clienteId_fkey" FOREIGN KEY ("clienteId")
    REFERENCES public.cliente ("idCliente") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pedido
    ADD CONSTRAINT "pedido_empleadoId_fkey" FOREIGN KEY ("empleadoId")
    REFERENCES public.empleado ("idEmpleado") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pedido
    ADD CONSTRAINT "pedido_mesaId_fkey" FOREIGN KEY ("mesaId")
    REFERENCES public.mesa ("idMesa") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.piso
    ADD CONSTRAINT "piso_sedeId_fkey" FOREIGN KEY ("sedeId")
    REFERENCES public.sede ("idSede") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.producto
    ADD CONSTRAINT "producto_cateProductoId_fkey" FOREIGN KEY ("cateProductoId")
    REFERENCES public."cateProducto" ("idCateProducto") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.producto
    ADD CONSTRAINT "producto_inventarioId_fkey" FOREIGN KEY ("inventarioId")
    REFERENCES public.inventario ("idInventario") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.receta
    ADD CONSTRAINT "receta_productoId_fkey" FOREIGN KEY ("productoId")
    REFERENCES public.producto ("idProducto") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."rolPermiso"
    ADD CONSTRAINT "rolPermiso_permisoId_fkey" FOREIGN KEY ("permisoId")
    REFERENCES public.permiso ("idPermiso") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."rolPermiso"
    ADD CONSTRAINT "rolPermiso_rolId_fkey" FOREIGN KEY ("rolId")
    REFERENCES public.rol ("idRol") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."sesionCaja"
    ADD CONSTRAINT "sesionCaja_cajaId_fkey" FOREIGN KEY ("cajaId")
    REFERENCES public.caja ("idCaja") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."soliInventario"
    ADD CONSTRAINT "soliInventario_sedeId_fkey" FOREIGN KEY ("sedeSolicitanteId")
    REFERENCES public.sede ("idSede") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."soliInventario"
    ADD CONSTRAINT "soliInventario_sedeProveedoraId_fkey" FOREIGN KEY ("sedeProveedoraId")
    REFERENCES public.sede ("idSede") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT "usuario_empleadoId_fkey" FOREIGN KEY ("empleadoId")
    REFERENCES public.empleado ("idEmpleado") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "usuario_empleadoId_key"
    ON public.usuario("empleadoId");


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT "usuario_rolId_fkey" FOREIGN KEY ("rolId")
    REFERENCES public.rol ("idRol") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
ALTER TABLE public.cliente
ADD COLUMN IF NOT EXISTS direccion text
DEFAULT ''::text;
ALTER TABLE public.mesa
ADD COLUMN IF NOT EXISTS capacidad integer
DEFAULT 4;
ALTER TABLE public.pedido
ADD COLUMN IF NOT EXISTS "nombreReferencial" character varying(255),
ADD COLUMN IF NOT EXISTS "cantidadPersonas" integer DEFAULT 1;

-- ALTER CLIENTE
ALTER TABLE public.cliente
ADD CONSTRAINT cliente_telefono_key UNIQUE (telefono);

ALTER TABLE public.pedido
ADD COLUMN IF NOT EXISTS "comprobanteUrl" text;